class Matrix(object):
    def reshape(self, nums, r, c):
        A = [x for row in nums for x in row]  #Convert the matrix into a list for later access
        return [A[i*c:(i+1)*c] for i in range(r)] if r*c == len(A) else nums  #Calculate according to the row, each row is a list, the starting coordinate of each row is i * c, the ending coordinate is (i + 1) * c, i is generated by range (r), that is, the new matrix has r Row.
 
if __name__ == '__main__':
    m = Matrix()
    nums = [[1, 2], [3, 4]]
    newNum = m.reshape(nums, 1, 4)
    print(newNum)
